
# ========== 相对路径配置（随便移动文件夹都能用） ==========
dir=./下载目录
input-file=./aria2.session
save-session=./aria2.session
log=NUL
file-log-level=off
console-log-level=warn

# ========== 基础下载设置 ==========
continue=true
file-allocation=none
max-concurrent-downloads=5
max-connection-per-server=16
split=64
min-split-size=4M

# ========== RPC 网页管理（AriaNg）无密码 ==========
enable-rpc=true
rpc-listen-port=6800
# rpc-secret=my_aria2_pwd
rpc-allow-origin-all=true
rpc-listen-all=true

# ========== 自动保存任务 下载完成后自动删除 .aria2 临时文件（核心） ==========
# 每30秒自动保存（防丢）
save-session-interval=30
# 每20秒保存.aria2进度文件
auto-save-interval=20
# 已完成也保存（重启不消失）
force-save=true
auto-file-renaming=false
allow-overwrite=true